### ISSUE TITLE
볼륨 매트릭스 탭에서 그래프 표시 및 데이터 저장 오류

### ISSUE THREAD

**Issue by dhslove** [ablecloud-team/ablestack-cloud#377]
#### 이슈 타입

 * 버그 및 오류 보고

#### 컴포넌트 이름

~~~
Storage, Glue Volume
~~~

#### ABLESTACK 버전

~~~
ABLESTACK 4.0
~~~

#### 구성

~~~
해당 없음
~~~

#### OS / 환경

~~~
Mac OS/Chrone
~~~

#### 이슈 내용

볼륨에 대한 메트릭스가 표시가 안됨. 볼륨 통계 자료가 저장안됨
다음과 같은 에러 메시지 표시됨.

~~~
2024-01-26 14:43:43,391 ERROR [c.c.s.StatsCollector] (StatsCollector-4:ctx-1a97c684) (logid:06827e72) Error trying to retrieve volume stats
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.indexOf(ImmutableCollections.java:170)
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.contains(ImmutableCollections.java:201)
	at com.cloud.server.StatsCollector$VolumeStatsTask.runInContext(StatsCollector.java:1793)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
~~~

#### 재현 과정

~~~
vm.disk.stats.retention.enabled 설정이 활성화 되어 있어야 함
vm.disk.stats.max.retention.time 이 설정되어 있어야 함
vm.disk.stats.interval 및 vm.disk.stats.interval.min이 설정되어 있어야 함

해당 설정 후 관리서버 재시작하면 볼륨 상세화면에 메트릭스가 표시됨
~~~

#### 기대한 결과

~~~
메트릭스가 표시되어야 함
~~~

#### 실제 결과

~~~
그래프가 정상 표시되지 않고 데이터(volume_stats)가 저장되지 않음
~~~

**Comment by jschoiRR** [comment]
작년 shareable 볼륨 테스트를 수작업으로 진행하였을 당시
volumes 테이블의  format컬럼의 항목이 Null로 입력되어 있어 발생하는 오류인것으로 확인했습니다.

volumes 테이블의 format 항목값을 null > RAW 값으로 입력시 해당 오류는 발생하지 않음
![image](https://github.com/ablecloud-team/ablestack-cloud/assets/77760789/2b43fabc-2b8c-435f-a697-92bc7b286cde)

**Comment by jschoiRR** [comment]
LivbirtComputeResource.java > getDiskPathFromDiskDef 의 
![image](https://github.com/ablecloud-team/ablestack-cloud/assets/77760789/9b318474-e930-497c-a582-3b864f669592)
병합 후 소스 누락 확인

볼륨 목록의 메트릭 정보(디스크 읽기, 쓰기, IOPS 데이터 등) 누락 관련 수정(https://github.com/ablecloud-team/ablestack-cloud/pull/358)
위 PR에서 수정된 소스가
최근 ablestack-diplo 브랜치에 누락된 부분확인

**Comment by jschoiRR** [comment]
![image](https://github.com/ablecloud-team/ablestack-cloud/assets/77760789/60e05946-fbbf-4715-96d8-f4642e0201e2)

LivbirtComputeResource.java(getDiskPathFromDiskDef 메소드) 소스 수정 후 
DB 데이터 수집 확인 완료

**Comment by dhslove** [comment]
수정 결과 확인했습니다. 이슈 닫습니다.
