### ISSUE TITLE
[Usage] Mold Usage 서버 DB 에러

### ISSUE THREAD

**Issue by dhslove** [ablecloud-team/ablestack-cloud#383]
#### 이슈 타입

 * 버그 및 오류 보고
 
#### 컴포넌트 이름

~~~
USAGE SERVER
~~~

#### ABLESTACK 버전

~~~
4.0
~~~

#### 구성

~~~
Usage Server 구성 및 실행 구성
~~~

#### OS / 환경

~~~
N/A
~~~

#### 이슈 내용

Usage 서버에서 스냅샷 사용량 측정 시 로그에 다음의 에러가 표시됨.

~~~
2024-01-29 12:15:05,021 ERROR [cloud.usage.UsageManagerImpl] (Usage-Job-1:null) (logid:) Exception in usage manager
com.cloud.utils.exception.CloudRuntimeException: DB Exception on: com.mysql.cj.jdbc.ClientPreparedStatement: SELECT snapshots.id, snapshots.data_center_id, snapshots.account_id, snapshots.domain_id, snapshots.volume_id, snapshots.disk_offering_id, snapshots.name, snapshots.status, snapshots.snapshot_type, snapshots.location_type, snapshots.type_description, snapshots.size, snapshots.created, snapshots.removed, snapshots.hypervisor_type, snapshots.version, snapshots.uuid, snapshots.min_iops, snapshots.max_iops FROM snapshots WHERE snapshots.id = 2  AND snapshots.removed IS NULL
        at com.cloud.utils.db.GenericDaoBase.findById(GenericDaoBase.java:1041)
        at com.cloud.storage.dao.SnapshotDaoImpl_EnhancerByCloudStack_aeca7a96.CGLIB$findById$80(<generated>)
        at com.cloud.storage.dao.SnapshotDaoImpl_EnhancerByCloudStack_aeca7a96_FastClassByCloudStack_daa87d54.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at com.cloud.utils.component.ComponentInstantiationPostProcessor$InterceptorDispatcher.intercept(ComponentInstantiationPostProcessor.java:122)
        at com.cloud.storage.dao.SnapshotDaoImpl_EnhancerByCloudStack_aeca7a96.findById(<generated>)
        at com.cloud.utils.db.GenericDaoBase.lockRow(GenericDaoBase.java:1018)
        at com.cloud.storage.dao.SnapshotDaoImpl_EnhancerByCloudStack_aeca7a96.CGLIB$lockRow$48(<generated>)
        at com.cloud.storage.dao.SnapshotDaoImpl_EnhancerByCloudStack_aeca7a96_FastClassByCloudStack_daa87d54.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at com.cloud.utils.component.ComponentInstantiationPostProcessor$InterceptorDispatcher.intercept(ComponentInstantiationPostProcessor.java:122)
        at com.cloud.storage.dao.SnapshotDaoImpl_EnhancerByCloudStack_aeca7a96.lockRow(<generated>)
        at com.cloud.utils.db.GenericDaoBase.findById(GenericDaoBase.java:964)
        at com.cloud.storage.dao.SnapshotDaoImpl_EnhancerByCloudStack_aeca7a96.CGLIB$findById$82(<generated>)
        at com.cloud.storage.dao.SnapshotDaoImpl_EnhancerByCloudStack_aeca7a96_FastClassByCloudStack_daa87d54.invoke(<generated>)
        at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at com.cloud.utils.component.ComponentInstantiationPostProcessor$InterceptorDispatcher.intercept(ComponentInstantiationPostProcessor.java:122)
        at com.cloud.storage.dao.SnapshotDaoImpl_EnhancerByCloudStack_aeca7a96.findById(<generated>)
        at com.cloud.usage.UsageManagerImpl.createSnapshotHelperEvent(UsageManagerImpl.java:1694)
        at com.cloud.usage.UsageManagerImpl.createHelperRecord(UsageManagerImpl.java:1052)
        at com.cloud.usage.UsageManagerImpl.parse(UsageManagerImpl.java:706)
        at com.cloud.usage.UsageManagerImpl.runInContextInternal(UsageManagerImpl.java:421)
        at com.cloud.usage.UsageManagerImpl$1.runInContext(UsageManagerImpl.java:363)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
        at com.cloud.usage.UsageManagerImpl.run(UsageManagerImpl.java:365)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLSyntaxErrorException: Table 'cloud_usage.snapshots' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
~~~

#### 재현 과정

~~~
systemctl status cloudstack-usage 상태 확인 후 
/var/log/cloudstack/usage/usage.log 내용의 Error 확인
~~~

#### 기대한 결과

~~~
정상 실행
~~~

#### 실제 결과

~~~
데이터베이스 에러 표시
~~~

**Comment by jschoiRR** [comment]
![스크린샷 2024-02-05 오후 12 21 05](https://github.com/ablecloud-team/ablestack-cloud/assets/77760789/b5af58c9-451a-4bb6-a54e-1bed65a82c85)

**UsageManagerImpl.java > createSnapshotHelperEvent 메소드부분**

````
SnapshotVO snapshotInstance = _snapshotDao.findById(snapId);

if (snapshotInstance != null && snapshotInstance.getSnapshotType() == Snapshot.Type.INTERNAL.ordinal()) {
     return;
}
````

https://github.com/apache/cloudstack/blob/main/usage/src/main/java/com/cloud/usage/UsageManagerImpl.java
**해당부분이 현재 cloudstack main branch에는 코드가 제거되있는 상태확인됨 
코드 제거시 위 같은 버그 발생하지 않음**

**Comment by dhslove** [comment]
해당 내용 반영해서 PR 바랍니다.
